name: Build and deploy Node.js app to Azure Web App - dynamic-marcetux

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies with legacy-peer-deps
        run: npm install --legacy-peer-deps
        working-directory: ./dynamic-amazon-demo

      - name: Install missing Babel plugin
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object
        working-directory: ./dynamic-amazon-demo

      - name: Fix ESLint issues
        run: npm run lint --if-present || true
        working-directory: ./dynamic-amazon-demo

      - name: Build project
        run: npm run build --if-present
        working-directory: ./dynamic-amazon-demo

      - name: Remove unnecessary files
        run: |
          rm -rf node_modules
          rm -rf tests
        working-directory: ./dynamic-amazon-demo

      - name: Zip artifact for deployment
        run: |
          zip -r ../release.zip .
        working-directory: ./dynamic-amazon-demo

      - name: Verify artifact exists
        run: ls -la release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Set SCM_DO_BUILD_DURING_DEPLOYMENT
        uses: azure/appservice-settings@v1
        with:
          app-name: 'dynamic-marcetux'
          app-settings-json: |
            {
              "SCM_DO_BUILD_DURING_DEPLOYMENT": "true"
            }
          mask-inputs: true

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6D508196FA1243D39E501CCB13BB7D6D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E76CE63D57D84B89A103DCD39A8BA3B9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_64392EE8EE4D4527B24F3AF63C708EF9 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dynamic-marcetux'
          slot-name: 'Production'
          package: .
